# Compose a postgres database together with the extension pgvector
services:
  db:
    hostname: vector_store
    container_name: vector_store
    image: ankane/pgvector
    ports:
     - 54320:5432
    environment:
      - POSTGRES_DB=vector_store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/pgvector/data:/var/lib/postgresql/data
      - ./db/pgvector/init/init.sql:/docker-entrypoint-initdb.d/init.sql